import {useCallback,useState} from "react";
import {useFocusEffect} from "@react-navigation/native";
import {Alert,Pressable,SafeAreaView,ScrollView,Text,TextInput,View} from "react-native";
import {router,useLocalSearchParams} from "expo-router";
import {supabase} from "../lib/supabase";
import {BRAND} from "../lib/brand";

type Contractor={id:string;name:string;specialty:string|null;unit:string|null;unit_rate:number|null};
export default function Contractors(){
  const {projectId}=useLocalSearchParams<{projectId?:string}>(); const [items,setItems]=useState<Contractor[]>([]); const [projectName,setProjectName]=useState("");
  const [name,setName]=useState(""); const [specialty,setSpecialty]=useState(""); const [unit,setUnit]=useState("مترمربع"); const [rate,setRate]=useState(""); const [busy,setBusy]=useState(false);
  const load=async()=>{let id=projectId; if(!id){const {data}=await supabase.from("projects").select("id,name").eq("status","active").limit(2);if((data||[]).length===1)id=data![0].id;else{setProjectName("ابتدا از فهرست پروژه‌ها یک پروژه انتخاب کن.");return;}} const {data:p}=await supabase.from("projects").select("name").eq("id",id).single();setProjectName(p?.name||"");const {data}=await supabase.from("contractors").select("id,name,specialty,unit,unit_rate").eq("project_id",id).order("created_at",{ascending:false});setItems(data||[])};
  useFocusEffect(useCallback(()=>{load()},[projectId]));
  const add=async()=>{if(!name.trim()||!projectId)return;setBusy(true);const {error}=await supabase.from("contractors").insert({project_id:projectId,name:name.trim(),specialty:specialty.trim()||null,unit:unit.trim()||"واحد",unit_rate:Number(rate)||0});setBusy(false);if(error){Alert.alert("ثبت پیمانکار ناموفق بود",error.message);return;}setName("");setSpecialty("");setRate("");load()};
  return <SafeAreaView style={{flex:1,backgroundColor:BRAND.bg,padding:20}}><ScrollView contentContainerStyle={{paddingBottom:40}}><Pressable onPress={()=>router.back()}><Text style={{color:BRAND.muted}}>← بازگشت</Text></Pressable><Text style={{color:BRAND.text,fontSize:28,fontWeight:"900" as const,marginTop:10}}>پیمانکاران</Text>{projectName&&<Text style={{color:BRAND.muted,marginTop:4}}>{projectName}</Text>}
  <View style={{marginTop:18,gap:10,backgroundColor:BRAND.surface,padding:16,borderRadius:18,borderWidth:1,borderColor:BRAND.border}}><TextInput value={name} onChangeText={setName} placeholder="نام پیمانکار" placeholderTextColor="#707986" style={styles.input}/><TextInput value={specialty} onChangeText={setSpecialty} placeholder="زمینه کاری، مثلاً گچ‌کار" placeholderTextColor="#707986" style={styles.input}/><TextInput value={unit} onChangeText={setUnit} placeholder="واحد، مثلاً مترمربع" placeholderTextColor="#707986" style={styles.input}/><TextInput value={rate} onChangeText={setRate} placeholder="نرخ واحد به تومان" keyboardType="numeric" placeholderTextColor="#707986" style={styles.input}/><Pressable disabled={busy||!projectId} onPress={add} style={[styles.primary,{opacity:(busy||!projectId)?0.5:1}]}><Text style={styles.primaryText}>{busy?"در حال ثبت...":"افزودن پیمانکار"}</Text></Pressable></View>
  <View style={{gap:10,marginTop:20}}>{items.map(c=><View key={c.id} style={styles.card}><Text style={styles.title}>{c.name}</Text><Text style={styles.sub}>{c.specialty||"بدون تخصص"} · {c.unit||"واحد"} · {Number(c.unit_rate||0).toLocaleString("fa-IR")} تومان</Text></View>)}</View></ScrollView></SafeAreaView>;
}
const styles={input:{color:BRAND.text,padding:14,borderWidth:1,borderColor:BRAND.border,borderRadius:12,backgroundColor:BRAND.bg},primary:{backgroundColor:BRAND.accent,padding:15,borderRadius:13},primaryText:{color:"#fff",textAlign:"center" as const,fontWeight:"900" as const},card:{backgroundColor:BRAND.surface,borderWidth:1,borderColor:BRAND.border,borderRadius:16,padding:16},title:{color:BRAND.text,fontWeight:"800" as const,fontSize:17},sub:{color:BRAND.muted,marginTop:3}};
